### ISSUE TITLE
RuntimeError: unable to instantiate 'File Filter.file_filter.FileFilterSetHighlightTypeCommand'

### ISSUE THREAD

**Issue by reagle** [vsc-cnst/SublimeTextFileFilter#7]
I'm not sure what happened, but the filter isn't working anymore.

```
The above exception was the direct cause of the following exception:

RuntimeError: unable to instantiate 'File Filter.file_filter.FileFilterSetFoldingTypeCommand'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 535, in create_window_commands
    o = cls(window)
  File "/Users/reagle/Library/Application Support/Sublime Text/Installed Packages/File Filter.sublime-package/file_filter.py", line 152, in __init__
    self.set_folding_type(SETTINGS.get('default_folding_style', None))
  File "/Users/reagle/Library/Application Support/Sublime Text/Installed Packages/File Filter.sublime-package/file_filter.py", line 217, in set_folding_type
    self.log.debug(self.get_state(folding_type))
  File "/Users/reagle/Library/Application Support/Sublime Text/Installed Packages/File Filter.sublime-package/file_filter.py", line 415, in get_state
    return f'args: {str(args):^{pad}},  folding_type: {self.folding_type.value:^{pad}}, highlight_type: {self.highlight_type.description:^{pad}}, regex: {regex:^{pad}}'
AttributeError: 'FileFilterSetHighlightTypeCommand' object has no attribute 'highlight_type'

The above exception was the direct cause of the following exception:

RuntimeError: unable to instantiate 'File Filter.file_filter.FileFilterSetHighlightTypeCommand'
```

Using FF 2.1.2 on ST stable 4180 on macOS 14.6.1 23G93 arm64.

**Comment by vsc-cnst** [comment]
Release 2.1.3 is out. it should resolve the issue
